# Generated by Django 6.0 on 2025-12-23 08:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='課號')),
                ('course_name', models.CharField(max_length=100, verbose_name='課名')),
                ('credits', models.IntegerField(default=3, verbose_name='學分')),
                ('description', models.TextField(blank=True, verbose_name='課程描述')),
                ('max_students', models.IntegerField(default=50, verbose_name='最大選修人數')),
                ('semester', models.CharField(default='2024-1', max_length=20, verbose_name='學期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '課程',
                'verbose_name_plural': '課程',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='學號')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='信箱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '學生',
                'verbose_name_plural': '學生',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='留言內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.course', verbose_name='課程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言者')),
            ],
            options={
                'verbose_name': '課程留言',
                'verbose_name_plural': '課程留言',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='教工編號')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='所屬部門')),
                ('bio', models.TextField(blank=True, verbose_name='教師簡介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '教師',
                'verbose_name_plural': '教師',
                'ordering': ['teacher_id'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_set', to='courses.teacher', verbose_name='任課教師'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '學生'), ('teacher', '教師'), ('admin', '管理者')], max_length=10, verbose_name='角色')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='學號')),
                ('teacher_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='教工編號')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='頭像')),
                ('bio', models.TextField(blank=True, verbose_name='個人簡介')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '用戶資料',
                'verbose_name_plural': '用戶資料',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='期中分數')),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='期末分數')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否選修中')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='選課時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='課程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_set', to=settings.AUTH_USER_MODEL, verbose_name='學生')),
            ],
            options={
                'verbose_name': '選課記錄',
                'verbose_name_plural': '選課記錄',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
